[versions]
# Java
java = "25"

# Plugins
graalvm-native = "0.11.4"
spotbugs-plugin = "6.4.8"
checkstyle = "10.20.1"
maven-publish = "0.36.0"

# Dependencies
jspecify = "1.0.0"
junit = "5.11.0"
poi = "5.5.1"

# Tools
jacoco = "0.8.14"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }

[plugins]
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
